const CIPHER = "TRPEADUHOGETOSOMNLGAHNSRSTOOCACHSNTTRHAFIEIHRTEGHYDFOOOSTHMNGTLVCGHHUSDYAAAMBRWONNHSWEATEANOCOUAOAFHDGWONMNRMVIDWUMCTFFNTANLBOCEOTHLTHASESECTEORHDDFPGODTGNDOABMWETDNNGORSTOROLDOASTHYTGRCYTODAIFIHTWRMTRIEELIHAHHIFOPTTMTTRCSHLEHEELSIIRLRAILDRRGHOEOLTSULPOLILPIRRLMETAETAEMWAHAMHEHEIHHRTEETILORAHITFURRIHMOEGVAFPSWCETEOSLEREWAIEKTHUANSONEEHEBEONWNYNEDAQOTUEHIETHEATTAKYLROOLZALONAASGOGARNNAHHLYEHLSLONTSAEHTSCOFLAHSASAEDEDNIODUYCOLAIAYENHASWILIERDHETFREOKWHFBTLRYDENNDEOETIAWLGDSEEESWSASIIISDUNHLAENNHESLAOSNTIEOFEZGYWDNNHOWIDATTTEESWRIYSOOGHTSCAHTTSALLIATTNPTKTSIHFATDELEFFWODILHELETHTIIIINUETLENGOTTENTRSNEIREOEMHEWTRAHAAAAHPELTEECTIWPTROUEEIDCEHWDTYDGDTARLRBNOEOSFMCPGSPESTIKAEHOIDIROEJNHWRYWTWISSMSMTUERHIFTNNFSLGEREEDLCAEUISILOSOTAITUATVOARDTBNSMTRNILTOSRCRIATLINNRSMEEEDRPGTEYTAUTTEHCTKRASISFMSKETNNOMIEIIIIHEMOENRSEATLDEOIURFICLIODAHIHU"
const COLUMNS = 6

const COMMON_WORDS = "THE OF AND TO A IN FOR IS ON THAT BY THIS WITH I YOU IT NOT OR BE ARE FROM AT AS YOUR ALL HAVE NEW MORE AN WAS WE WILL HOME CAN US ABOUT IF PAGE MY HAS SEARCH FREE BUT OUR ONE OTHER DO NO INFORMATION TIME THEY SITE HE UP MAY WHAT WHICH THEIR NEWS OUT USE ANY THERE SEE ONLY SO HIS WHEN CONTACT HERE BUSINESS WHO WEB ALSO NOW HELP GET PM VIEW ONLINE C E FIRST AM BEEN WOULD HOW WERE ME S SERVICES SOME THESE CLICK ITS LIKE SERVICE X THAN FIND PRICE DATE BACK TOP PEOPLE HAD LIST NAME JUST OVER STATE YEAR DAY INTO EMAIL TWO HEALTH N WORLD RE NEXT USED GO B WORK LAST MOST PRODUCTS MUSIC BUY DATA MAKE THEM SHOULD PRODUCT SYSTEM POST HER CITY T ADD POLICY NUMBER SUCH PLEASE AVAILABLE COPYRIGHT SUPPORT MESSAGE AFTER BEST SOFTWARE THEN JAN GOOD VIDEO WELL D WHERE INFO RIGHTS PUBLIC BOOKS HIGH SCHOOL THROUGH M EACH LINKS SHE REVIEW YEARS ORDER VERY PRIVACY BOOK ITEMS COMPANY R READ GROUP SEX NEED MANY USER SAID DE DOES SET UNDER GENERAL RESEARCH UNIVERSITY JANUARY MAIL FULL MAP REVIEWS PROGRAM LIFE KNOW GAMES WAY DAYS MANAGEMENT P PART COULD GREAT UNITED HOTEL REAL F ITEM INTERNATIONAL CENTER EBAY MUST STORE TRAVEL COMMENTS MADE DEVELOPMENT REPORT OFF MEMBER DETAILS LINE TERMS BEFORE HOTELS DID SEND RIGHT TYPE BECAUSE LOCAL THOSE USING RESULTS OFFICE EDUCATION NATIONAL CAR DESIGN TAKE POSTED INTERNET ADDRESS COMMUNITY WITHIN STATES AREA WANT PHONE DVD SHIPPING RESERVED SUBJECT BETWEEN FORUM FAMILY L LONG BASED W CODE SHOW O EVEN BLACK CHECK SPECIAL PRICES WEBSITE INDEX BEING WOMEN MUCH SIGN FILE LINK OPEN TODAY TECHNOLOGY SOUTH CASE PROJECT SAME PAGES UK VERSION SECTION OWN FOUND SPORTS HOUSE RELATED SECURITY BOTH G COUNTY AMERICAN PHOTO GAME MEMBERS POWER WHILE CARE NETWORK DOWN COMPUTER SYSTEMS THREE TOTAL PLACE END FOLLOWING DOWNLOAD H HIM WITHOUT PER ACCESS THINK NORTH RESOURCES CURRENT POSTS BIG MEDIA LAW CONTROL WATER HISTORY PICTURES SIZE ART PERSONAL SINCE INCLUDING GUIDE SHOP DIRECTORY BOARD LOCATION CHANGE WHITE TEXT SMALL RATING RATE GOVERNMENT CHILDREN DURING USA RETURN STUDENTS V SHOPPING ACCOUNT TIMES SITES LEVEL DIGITAL PROFILE PREVIOUS FORM EVENTS LOVE OLD JOHN MAIN CALL HOURS IMAGE DEPARTMENT TITLE DESCRIPTION NON K Y INSURANCE ANOTHER WHY SHALL PROPERTY CLASS CD STILL MONEY QUALITY EVERY LISTING CONTENT COUNTRY PRIVATE LITTLE VISIT SAVE TOOLS LOW REPLY CUSTOMER DECEMBER COMPARE MOVIES INCLUDE COLLEGE VALUE ARTICLE YORK MAN CARD JOBS PROVIDE J FOOD SOURCE AUTHOR DIFFERENT PRESS U LEARN SALE AROUND PRINT COURSE JOB CANADA PROCESS TEEN ROOM STOCK TRAINING TOO CREDIT POINT JOIN SCIENCE MEN CATEGORIES ADVANCED WEST SALES LOOK ENGLISH LEFT TEAM ESTATE BOX CONDITIONS SELECT WINDOWS PHOTOS GAY THREAD WEEK CATEGORY NOTE LIVE LARGE GALLERY TABLE REGISTER HOWEVER JUNE OCTOBER NOVEMBER MARKET LIBRARY REALLY ACTION START SERIES MODEL FEATURES AIR INDUSTRY PLAN HUMAN PROVIDED TV YES REQUIRED SECOND HOT ACCESSORIES COST MOVIE FORUMS MARCH LA SEPTEMBER BETTER SAY QUESTIONS JULY YAHOO GOING"

const common_words_arr = COMMON_WORDS.split(" ")

function main(){
  var columnar = split()
  decode(columnar)
}

/**
* This fucntion splits the cipher into a two dimensional array by calculating
* the size of each array done by dividing the cipher length by the columns.
**/
function split(){
  var splice_length = CIPHER.length / COLUMNS
  var columnar = [[], []]
  var cipher_array = CIPHER.split('')

  var j = 0
  for (var i = 0; i < cipher_array.length; i += splice_length) {
    columnar[j] = cipher_array.slice(i, i + splice_length)
    j++
  }

  return columnar
}

function shuffle(array) {
  array.sort(() => Math.random() - 0.5);
}

/**
* This function takes in a two dimensional array for which it will try to
* provide a soltion by shuffling the column orderings and checking for a
* defined score. If that score is met, then the solution is returned.
**/
function decode(columnar){
  var decoded = false
  var decoded_array = []
  var shuffled = 0;
  while(!decoded){
    var pos = 0
    for(var i = 0; i < columnar[0].length; i++){
      for(var j = 0; j < columnar.length; j++){
        decoded_array[pos++] = columnar[j][i];
      }
    }

    var solution = decoded_array.join('')
    var score = find_score(solution)
    console.log(score)
    // look for 20% match with the 500 most common English words
    if(score > 20){
      decoded = true
    } else{
      shuffled++
      shuffle(columnar)
    }
  }

  console.log("Proposed solution: " + decoded_array.join(""))
  console.log("Iterations taken: " + shuffled)
}

/**
* Little function that finds out how many of the common words appear in the
* brute-forced solution and devides the count by the size of common_words_arr
* to find out the percentage. The higher the score, the more likely this is
* the correct brute-force solution.
**/
function find_score(solution){
  var matches = 0
  var score = 0
  for(var i = 0; i < common_words_arr.length; i++){
    if(solution.includes(common_words_arr[i])){
      matches++
    }
  }
  score = (matches / common_words_arr.length) * 100

  return score
}

/**
* Shuffle that works for two dimensional arrays. This type of shuffle is ALSO
* known as the Knuth shuffle.
**/
function kshuffle(arr) {
    var rand, temp, i;
    for (i = arr.length - 1; i > 0; i -= 1) {
        rand = Math.floor((i + 1) * Math.random());//get random between zero and i (inclusive)
        temp = arr[rand];//swap i and the zero-indexed number
        arr[rand] = arr[i];
        arr[i] = temp;
    }
    return arr;
}

main()
